// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PxlTeambuilderApi.Data;

namespace PxlTeambuilderApi.Data.Migrations
{
    [DbContext(typeof(PxlTeamBuilderContext))]
    [Migration("20190105122257_rework-relationship-user-project-group")]
    partial class reworkrelationshipuserprojectgroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("ProjectId");

                    b.HasKey("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("MaxStudentsPerGroup");

                    b.Property<string>("Title");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.UserProjectDetail", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("ProjectId");

                    b.Property<string>("GroupId");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("UserProjectDetails");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.Group", b =>
                {
                    b.HasOne("PxlTeambuilderApi.Data.Domain.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.UserProjectDetail", b =>
                {
                    b.HasOne("PxlTeambuilderApi.Data.Domain.Group", "Group")
                        .WithMany("UserProjectDetails")
                        .HasForeignKey("GroupId");

                    b.HasOne("PxlTeambuilderApi.Data.Domain.Project", "Project")
                        .WithMany("UserProjectDetails")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PxlTeambuilderApi.Data.Domain.User", "User")
                        .WithMany("UserProjectDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
