// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PxlTeambuilderApi.Data;

namespace PxlTeambuilderApi.Data.Migrations
{
    [DbContext(typeof(PxlTeamBuilderContext))]
    partial class PxlTeamBuilderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("ProjectId");

                    b.HasKey("GroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("MaxStudentsPerGroup");

                    b.Property<string>("Title");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.HasKey("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.UserGroup", b =>
                {
                    b.Property<string>("Email");

                    b.Property<string>("GroupId");

                    b.HasKey("Email", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.Group", b =>
                {
                    b.HasOne("PxlTeambuilderApi.Data.Domain.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("PxlTeambuilderApi.Data.Domain.UserGroup", b =>
                {
                    b.HasOne("PxlTeambuilderApi.Data.Domain.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("Email")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PxlTeambuilderApi.Data.Domain.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
